### PR TITLE
[FIXED JENKINS-29698] Protect from race conditions

### PR DESCRIPTION
**Pull request by KostyaSha**

### CODE REVIEW

**Comment by KostyaSha** [comment]
Build failed because repository is not configured or @timols didn't publish gitlab-api.

**Comment by timols** [comment]
@KostyaSha Can you reopen your pull request against the https://github.com/timols/jenkins-gitlab-merge-request-builder-plugin repository?

**Comment by KostyaSha** [comment]
No. One of the reasons why jenkins hosts plugins under jenkinsci - easy collaboration + other infra helpers.

**Comment by timols** [comment]
@KostyaSha since the primary source of development effort for this plugin is in the primary repository (not this fork), that is the only place I'll be accepting the PR. If you'd like me to merge it in, I urge you to do so there.

**Comment by oleg-nenashev** [comment]
@timols 
I disagree with this approach, but it's up to you. In any case, you should document it on the plugin's Wiki page and in the README.md in order to avoid further confusions

**Comment by lanwen** [comment]
@timols :-1: what for you need to maintain two repos instead of only one in common place?

**Comment by timols** [comment]
Thanks for the feedback @oleg-nenashev and @lanwen but at the time of creating this plugin the instructions (https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org) did not indicate that I needed to transfer the ownership of the source code I wrote to jenkinsci.

This is the first time in approximately 2 years this has ever happened. Given that it is such an extremely rare occurrence and due to @KostyaSha not taking a moment to go to the original source, I don't see the need to document this separately. Many contributions in the form of PRs have been contributed to the primary repository without ever experiencing any problems, so @lanwen I am not maintaining two repos.

**Comment by KostyaSha** [comment]
As @timols blocked me on his fork, will reply here. @timols picked my changes without asking my permissions to changes authorship in this commit https://github.com/timols/jenkins-gitlab-merge-request-builder-plugin/commit/45e55c27bbb665ab344e64d73f85a26b515cff27

IMHO such plugins should be filtered out from update center into some 3d party repositories.
cc @daniel-beck

**Comment by oleg-nenashev** [comment]
@timols 

> at the time of creating this plugin the instructions (https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkinsci.org) did not indicate that I needed to transfer the ownership of the source code I wrote to jenkinsci.

Actually there's no such requirements. Even if you move the code to jenkinsci, you still own it. It's only the recommended standard place. There're periodic discussions about somehow distinguishing jenkinsci-located and external plugins in update centers, but there is no final decisions by now. Jenkins contributors **are not requested** to use the jenkinsci organization, it's just a **recommendation**

@timols 
Probably updating the pom.xml is enough. It should point to the real repo in order to make Jenkins Wiki to point to the right repo. Currently the link in the summary table is broken

**Comment by KostyaSha** [comment]
@oleg-nenashev the number of plugins is already huge from time when such rules wrote, many companies hosting it without any problems. If somebody wants to live alone, then they can do. I think such topic should be moved to jenkins meeting.

**Pull request closed without merging**
